-- 1) Project content table
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  industry text,
  tags text[] default '{}',
  categories text[] default '{}',
  card_image text,
  card_alt text,
  hero_image text,
  hero_alt text,
  year text,
  role text,
  client_name text,
  deliverables text,
  hero_subtitle text,
  hero_summary text,
  detail_product text,
  detail_channels text,
  detail_overview text,
  context_paragraph_1 text,
  context_paragraph_2 text,
  context_bullets text[] default '{}',
  results jsonb default '[]'::jsonb,
  reflection text[] default '{}',
  sort_order int default 0,
  is_published boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2) Updated-at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_projects_updated_at on public.projects;
create trigger trg_projects_updated_at
before update on public.projects
for each row
execute function public.set_updated_at();

-- 3) Public read policy (for static website)
alter table public.projects enable row level security;

drop policy if exists "Public can read published projects" on public.projects;
create policy "Public can read published projects"
on public.projects
for select
to anon
using (is_published = true);

-- 4) Storage bucket for images
insert into storage.buckets (id, name, public)
values ('project-images', 'project-images', true)
on conflict (id) do nothing;

-- 5) Public read policy for project image bucket
drop policy if exists "Public can read project images" on storage.objects;
create policy "Public can read project images"
on storage.objects
for select
to anon
using (bucket_id = 'project-images');
